backend:
  name: git-gateway

media_folder: source/images/uploads
public_folder: /images/uploads

collections:
  - label: "Links"
    name: "links"
    files:
      - label: "Links to Recipes"
        name: "links"
        extension: "yml"
        file: "source/data/links.yml"
        fields:
          - label: "Recipes"
            name: "recipes"
            widget: "list"
            allow_add: true
            collapsed: true
            fields:
              - {label: Link, name: link, widget: string}
              - {label: Image, name: image, widget: image}
